# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81cced7dd6845bde06582d112ec6c1e61e38623455f4704749ca5f5f93c173dfa6e68c0dd21fb3af45f2333a67101bd4f75ce29da17ded98c029c84794a2afb3

test:
  secret_key_base: 1d51835fbe505483558a8c2d3760c135abaed187190ad629203a67aef44cad7de94365815018cc49dc336d4bf83f984e0bbf7c012526c43492969b9669e79ed4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
